export const LOGIN = '/'
export const ADMIN_USERS = '/admin/users'
export const ADMIN_PRODUCTS = '/admin/products'
export const WAITER_MENU = '/menu'
export const WAITER_STATUS = '/status'
export const ORDERS = '/orders'